# Распределение товаров по торговым точкам через роевой интеллект

## Библиотеки

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from time import time

## Эвристики

Влияние продаж

In [2]:
sales_factor = 0.001

Влияние загруженности

In [3]:
load_factor = 0.0009

Так как товаров очень много, то при умножении суммы на константу могут получится слишком большие значения, из-за чего обновление феромонов будет гигантским. Потому нужно брать влияния продаж и загруженности в пределах 0.001

Сколько итераций считать

In [4]:
iterations_count = 100

Ранняя остановка. Если лучшее решение не менялось на протяжении указанного кол-ва итераций, то останваливаем алгоритм. Значение 0 значит без ранней остановки

In [5]:
early_stopping = 10

Если нынешнее лучшее решение не больше предыдущего хотя бы на эпсилон, то лучшее решение не обновляется

In [6]:
epsilon = 10**-4

Максимальная скорость познавательного самообучения

In [7]:
max_speed_research = 2.05

Максимальная скорость социального самообучения

In [8]:
max_speed_social = 2.05

Коэффициент предела скорости. То есть новый предел скорости будет velocity_limit_mult * v, где v - объём товара в закрывающемся магазине

In [9]:
velocity_limit_mult = 0.2

Коэффициент начальной скорости. Не должен быть больше speed_limit_mult

In [10]:
initial_velocity_mult = 0.1

Коэффициент скорости выталкивания перегрузки. Скорость частицы уменьшается на эту скорость

In [11]:
overflow_velocity_mult = 0.1

Коэффициент перегрузки. Позиция частицы насильно сдвигается на значение перегрузку

In [12]:
overflow_position_mult = 0.2

Важно, чтобы сумма максимальный скоростей самообучения была больше 4

Коэффициент $\alpha ∈ (0, 1)$, контролирует близость коэффициента сужения к максимуму

In [13]:
alpha = 0.9
shrink = 2 * alpha / (max_speed_research + max_speed_social - 2)

Число частиц

In [14]:
particle_count = 100

## Подгрузка датасета

In [15]:
col_vol = "Объём товара в закрывающемся магазине (V)"
col_maxcap = "Максимальная вместимость товара в магазине (M)"
col_item = "Код товара"
col_store = "Магазин"
col_remain = "Остаток товара в магазине (R)"
col_sales = "Продажи товара в магазине (S)"
col_dist = "Распределение частиц"

In [16]:
items = pd.read_csv(r"./filtered_datasets/items_closing_store.csv", sep=";")
items = items.set_index([col_item, col_store])
items

                    Объём товара в закрывающемся магазине (V)  \
Код товара Магазин
226249     54                                            10.0
           56                                            10.0
           57                                            10.0
           60                                            10.0
           61                                            10.0
...                                                       ...
239388     95                                            26.0
239397     38                                            12.0
239398     38                                            13.0
239515     38                                            42.0
239516     38                                            42.0

                    Продажи товара в магазине (S)  \
Код товара Магазин
226249     54                            1.379157
           56                            0.943567
           57                            0.857143
           60                            0.406742
           61                            0.713024
...                                           ...
239388     95                            1.500000
239397     38                            1.116279
239398     38                            2.023256
239515     38                            1.796296
239516     38                            1.740741

                    Максимальная вместимость товара в магазине (M)  \
Код товара Магазин
226249     54                                                    8
           56                                                    8
           57                                                    8
           60                                                    8
           61                                                    8
...                                                            ...
239388     95                                                   25
239397     38                                                   24
239398     38                                                   24
239515     38                                                   30
239516     38                                                   24

                    Остаток товара в магазине (R)
Код товара Магазин
226249     54                                16.0
           56                                22.0
           57                                19.0
           60                                28.0
           61                                22.0
...                                           ...
239388     95                                20.0
239397     38                                21.0
239398     38                                45.0
239515     38                                35.0
239516     38                                28.0

[413689 rows x 4 columns]

Со всем датасетом работать очень медленно. Гораздо лучше будет сделать несколько матриц

$i$ - товар, $i ∈ [1, N]$, $N$ - кол-во товаров

$j$ - магазин, $j ∈ [1, M]$, $M$ - кол-во магазинов

*closing_volume* - вектор размерности $N×1$, показывает кол-во товара $i$ в закрывающемся магазине

*sales* - матрица размерности $N×M$, показывает продажи товара $i$ в магазине $j$

*maxcap* - матрица размерности $N×M$, показывает вместимость на полках товара $i$ в магазине $j$

*remains* - матрица размерности $N×M$, показывает остатки товара $i$ в магазине $j$

*pheromones* - матрица размерности $N×M$, показывает феромоны для распределения товара $i$ в магазин $j$

Если товар $i$ не числится в магазине $j$, то тогда соответственные значения $(i, j)$ во всех матрицах равны 0

In [17]:
items_id = items.index.get_level_values(0).unique().values
N = items_id.shape[0]
N

5366

In [18]:
stores_id = items.index.get_level_values(1).unique().values
M = stores_id.shape[0]
M

98

Переиндексация для создания пар $(i, j)$

In [19]:
full_index = pd.MultiIndex.from_product([items_id, stores_id], names=[col_item, col_store])
df_full = items.reindex(full_index)
df_full

                    Объём товара в закрывающемся магазине (V)  \
Код товара Магазин
226249     54                                            10.0
           56                                            10.0
           57                                            10.0
           60                                            10.0
           61                                            10.0
...                                                       ...
239221     88                                             NaN
           105                                            NaN
           29                                             NaN
           27                                             NaN
           113                                           17.0

                    Продажи товара в магазине (S)  \
Код товара Магазин
226249     54                            1.379157
           56                            0.943567
           57                            0.857143
           60                            0.406742
           61                            0.713024
...                                           ...
239221     88                                 NaN
           105                                NaN
           29                                 NaN
           27                                 NaN
           113                           0.302326

                    Максимальная вместимость товара в магазине (M)  \
Код товара Магазин
226249     54                                                  8.0
           56                                                  8.0
           57                                                  8.0
           60                                                  8.0
           61                                                  8.0
...                                                            ...
239221     88                                                  NaN
           105                                                 NaN
           29                                                  NaN
           27                                                  NaN
           113                                                10.0

                    Остаток товара в магазине (R)
Код товара Магазин
226249     54                                16.0
           56                                22.0
           57                                19.0
           60                                28.0
           61                                22.0
...                                           ...
239221     88                                 NaN
           105                                NaN
           29                                 NaN
           27                                 NaN
           113                                5.0

[525868 rows x 4 columns]

Превращаем всё теперь в матрицы

In [20]:
closing_volume = items.groupby(level=0, sort=False).first()[col_vol].values
sales = df_full[col_sales].values.reshape(N, M)
maxcap = df_full[col_maxcap].values.reshape(N, M)
remains = df_full[col_remain].values.reshape(N, M)

Заполняем пропуски нулями

In [21]:
sales = np.nan_to_num(sales, nan=0)
maxcap = np.nan_to_num(maxcap, nan=0)
remains = np.nan_to_num(remains, nan=0)

## Рой частиц

### Частица

Так как рой частиц работает с действительными числами, а распределение - это только целые числа, то нужно сначала округлить значения, а потом восстановить (т.е. repair)

repair работает следующим образом:

1. Сначала исходное распределение с действительными значениями округляем в меньшую сторону
2. Эта операция может лишить нас товаров, потому находим разницу между тем, сколько товаров распределить можно всего, и сколько распределили мы после округления
3. Затем считаем потерянную дробную часть и сортируем в порядке убывания. Таким образом самые большие потерянные дробные части идут впереди
4. Находим индексы тех распределений, где больше всего было потеряно товаров. В numpy шаг 3 и 4 делаются сразу через argsort
5. Теперь осталось добавить по предмету там, где нужнее всего
6. Если же разница товаров отрицательная, то в шаге 3 сортируем в порядке возрастания, чтобы получить самые большие добавленные части. Потом же просто отнимаем эти товары

In [22]:
def particle_function(particle_position):    
    x, v, s, m, r = particle_position, closing_volume, sales, maxcap, remains
    c = np.zeros((N, M), dtype=np.int64)  # само распределение

    for i in range(N):  # repair      
        c[i] = np.floor(x[i]).astype(np.int64)  # округление до нижней границы
        item_loss = int(v[i] - np.sum(c[i]))  # сколько товаров таким образом потеряли

        if item_loss > 0:
            fractional = x[i] - c[i]  # дробные части
            indexes = np.argsort(-fractional)  # сортировка по значениям дробных частей в порядке убывания
            c[i][indexes[:item_loss]] += 1  # докинули товары там, где это важнее всего
                
        elif item_loss < 0:
            fractional = x[i] - c[i]  # дробные части
            indexes = np.argsort(fractional)  # сортировка по значениям дробных частей в порядке возрастания
            c[i][indexes[:-item_loss]] -= 1  # убираем товары оттуда, где это важноо всего

    sales_rating = sales_factor * (c + r) * s / (1 + r)

    load_rating = np.clip((c + r - m), a_min=0.0, a_max=None)  # убираем штраф, если нет перегрузки
    np.divide(load_rating, m, out=load_rating, where=m > 0)  # чтобы не поделить на 0
    load_rating *= load_factor
    
    total_rating = np.sum(sales_rating - load_rating)  # оценка решения
    
    return total_rating, c

### Рой

In [23]:
def particle_swarm_optimization():
    # Здесь индексы None делают здесь из одномерного массива трёхмерные особым образом, разберём на примере
    # Было a = [1, 2, 3]. Сделали b = a[None, :, None]. Получили b = [[[1], [2], [3]]]. Теперь a[0] == b[0][0][0], a[1] == b[0][0][1] и т.д.
    
    particle_positions = np.random.rand(particle_count, N, M)  # случайные значения от 0 до 1 для начальных позиций
    sum_positions = np.sum(particle_positions, axis=2, keepdims=True)  # сумма по товарам
    particle_positions = np.divide(particle_positions, sum_positions, out=np.zeros((particle_count, N, M), dtype=np.float64), where= sum_positions != 0.0)  # потом делаем равномерное распределение, чтобы не превысить кол-во товара в закрывающемся магазине 
    particle_positions *= closing_volume[None, :, None]  # получим таким образом начальные позиции в границах товаров
    
    in_stock = (maxcap > 0)[None, :]  # т.е. здесь товары действительно находятся в продаже
    particle_positions *= in_stock  # чтобы не считать там, где товары не продаются

    max_velocity = closing_volume[None, :, None]*velocity_limit_mult  # предел скорости
    initial_velocity = closing_volume[None, :, None]*initial_velocity_mult  # предел начальной скорости
    particle_velocities = np.random.uniform(-initial_velocity, initial_velocity, size=(particle_count, N, M))  # начальная скорость
    particle_velocities *= in_stock  # чтобы не считать там, где товары не продаются
    
    best_positions = np.zeros((particle_count, N, M), dtype=np.float64)
    best_ratings = np.full(particle_count, np.nan)  # лучшие оценки лучших позиций
    best_distributions = np.zeros((particle_count, N, M), dtype=np.int64)  # лучшие распределения (целочисленные)
    
    neighbors = np.array([((i-1) % particle_count, (i+1) % particle_count) for i in range(particle_count)], dtype=np.int64)  # кольцевая топология - два соседа для каждой частицы
    
    no_improvements = 0
    total_best_rating, total_best_index = None, None

    for i in range(iterations_count):
        print(f"\nIteration {i+1} out of {iterations_count}")

        iter_time = time()

        for particle in range(particle_count):  # каждая частица делает repair, затем считает оценку своего решения
            particle_rating, particle_distribution = particle_function(particle_positions[particle])

            if np.isnan(best_ratings[particle]) or particle_rating > best_ratings[particle]:  # обновляем лучшие положения частиц
                best_ratings[particle] = particle_rating
                best_positions[particle] = particle_positions[particle]  # изначально, лучшее положение каждой частицы - это её начальное положение
                best_distributions[particle] = particle_distribution

        print(f"Ratings for {particle_count} particles updated, took: {time() - iter_time}")

        current_best_index = np.argmax(best_ratings)
        current_best_rating = best_ratings[current_best_index]
        no_improvements += 1

        print("Best rating for the current iteration:", current_best_rating)

        if total_best_rating is None or total_best_index is None or (current_best_rating - total_best_rating) >= epsilon:
            total_best_rating = current_best_rating
            total_best_index = current_best_index
            no_improvements = 0

        print("Total best rating:", total_best_rating)

        if early_stopping > 0 and no_improvements >= early_stopping:
            print("Early stopping")
            break

        iter_time = time()
        
        for particle in range(particle_count):  # считаем обновление скоростей и позиций
            left_neighbor, right_neighbor = neighbors[particle]
            best_neighbor = 0

            if best_ratings[left_neighbor] > best_ratings[right_neighbor]:  # находим индекс лучшего соседа
                best_neighbor = left_neighbor

            else:
                best_neighbor = right_neighbor

            b = best_positions[particle]
            h = best_positions[best_neighbor]
            f1 = np.random.rand(N, M) * max_speed_research
            f2 = np.random.rand(N, M) * max_speed_social

            # np.clip((particle_positions[particle] + remains - maxcap), a_min=0.0, a_max=None) - это и есть overflow, т. е. перегрузка

            particle_velocities[particle] = shrink * particle_velocities[particle] + f1 * (b - particle_positions[particle]) + f2 * (h - particle_positions[particle])  # формула изменения скорости
            particle_velocities[particle] -= np.clip((particle_positions[particle] + remains - maxcap), a_min=0.0, a_max=None) * overflow_velocity_mult  # скорость выталкивания частицы при перегрузке
            particle_velocities[particle] = np.clip(particle_velocities[particle], min=-max_velocity, max=max_velocity)  # ограничиваем скорость
            
            particle_positions[particle] += particle_velocities[particle]  # перемещение частицы
            particle_positions[particle] -= np.clip((particle_positions[particle] + remains - maxcap), a_min=0.0, a_max=None) * overflow_position_mult  # напрямую выталкиваем частицу при перегрузке
            particle_positions[particle] = np.clip(particle_positions[particle], a_min=0.0, a_max=None)  # позиции не должны быть отрицательными
            
            items_sum = np.sum(particle_positions[particle], axis=1, keepdims=True)  # сумма товаров по магазинам
            adjust_positions = np.divide(closing_volume[:, None], items_sum, out=np.zeros((N, M), dtype=np.float64), where= items_sum != 0.0)  # коэффициент, во сколько раз количество товара в закрывающемся магазине больше / меньше, чем в распределении
            particle_positions[particle] *= adjust_positions  # сдвигаем позиции так, чтобы их сумма была равна кол-ву товара в закрывающемся магазине
  
    return total_best_rating, best_distributions[total_best_index]

In [24]:
time_start = time()
best_rating, best_solution = particle_swarm_optimization()

Iteration 1 out of 100
Ratings for 100 particles updated, took: 8.214381694793701
Best rating for the current iteration: 47.4075090574304
Total best rating: 47.4075090574304

Iteration 2 out of 100
Ratings for 100 particles updated, took: 7.790458679199219
Best rating for the current iteration: 56.824498278409735
Total best rating: 56.824498278409735

Iteration 3 out of 100
Ratings for 100 particles updated, took: 7.82852578163147
Best rating for the current iteration: 58.29985824278686
Total best rating: 58.29985824278686

Iteration 4 out of 100
Ratings for 100 particles updated, took: 7.770237922668457
Best rating for the current iteration: 59.23964260999487
Total best rating: 59.23964260999487

Iteration 5 out of 100
Ratings for 100 particles updated, took: 7.901870489120483
Best rating for the current iteration: 61.25129257464659
Total best rating: 61.25129257464659

Iteration 6 out of 100
Ratings for 100 particles updated, took: 7.835295915603638
Best rating for the current iteration: 61.40802006259537
Total best rating: 61.40802006259537

Iteration 7 out of 100
Ratings for 100 particles updated, took: 7.837323904037476
Best rating for the current iteration: 62.451043223589096
Total best rating: 62.451043223589096

Iteration 8 out of 100
Ratings for 100 particles updated, took: 7.741207122802734
Best rating for the current iteration: 63.40605979918267
Total best rating: 63.40605979918267

Iteration 9 out of 100
Ratings for 100 particles updated, took: 7.743668556213379
Best rating for the current iteration: 64.30745950756835
Total best rating: 64.30745950756835

Iteration 10 out of 100
Ratings for 100 particles updated, took: 7.762638807296753
Best rating for the current iteration: 64.97346426484688
Total best rating: 64.97346426484688

Iteration 11 out of 100
Ratings for 100 particles updated, took: 7.761317729949951
Best rating for the current iteration: 65.17523375164691
Total best rating: 65.17523375164691

Iteration 12 out of 100
Ratings for 100 particles updated, took: 7.7451887130737305
Best rating for the current iteration: 65.3831162902006
Total best rating: 65.3831162902006

Iteration 13 out of 100
Ratings for 100 particles updated, took: 7.734301328659058
Best rating for the current iteration: 65.78332719445072
Total best rating: 65.78332719445072

Iteration 14 out of 100
Ratings for 100 particles updated, took: 7.750748634338379
Best rating for the current iteration: 65.87740568082882
Total best rating: 65.87740568082882

Iteration 15 out of 100
Ratings for 100 particles updated, took: 7.91599178314209
Best rating for the current iteration: 66.21138495796222
Total best rating: 66.21138495796222

Iteration 16 out of 100
Ratings for 100 particles updated, took: 8.001200199127197
Best rating for the current iteration: 66.21138495796222
Total best rating: 66.21138495796222

Iteration 17 out of 100
Ratings for 100 particles updated, took: 7.8254172801971436
Best rating for the current iteration: 66.32299993269613
Total best rating: 66.32299993269613

Iteration 18 out of 100
Ratings for 100 particles updated, took: 7.793806314468384
Best rating for the current iteration: 66.50991909632826
Total best rating: 66.50991909632826

Iteration 19 out of 100
Ratings for 100 particles updated, took: 7.790950298309326
Best rating for the current iteration: 66.57377505316632
Total best rating: 66.57377505316632

Iteration 20 out of 100
Ratings for 100 particles updated, took: 7.9199323654174805
Best rating for the current iteration: 66.61050302993252
Total best rating: 66.61050302993252

Iteration 21 out of 100
Ratings for 100 particles updated, took: 7.828523397445679
Best rating for the current iteration: 66.72715563585973
Total best rating: 66.72715563585973

Iteration 22 out of 100
Ratings for 100 particles updated, took: 7.8579113483428955
Best rating for the current iteration: 66.83033403911358
Total best rating: 66.83033403911358

Iteration 23 out of 100
Ratings for 100 particles updated, took: 7.771440744400024
Best rating for the current iteration: 66.900970218119
Total best rating: 66.900970218119

Iteration 24 out of 100
Ratings for 100 particles updated, took: 7.766220331192017
Best rating for the current iteration: 67.0966742077093
Total best rating: 67.0966742077093

Iteration 25 out of 100
Ratings for 100 particles updated, took: 7.774751663208008
Best rating for the current iteration: 67.10241326574987
Total best rating: 67.10241326574987

Iteration 26 out of 100
Ratings for 100 particles updated, took: 7.835678815841675
Best rating for the current iteration: 67.31319937398294
Total best rating: 67.31319937398294

Iteration 27 out of 100
Ratings for 100 particles updated, took: 7.780468463897705
Best rating for the current iteration: 67.44361954452641
Total best rating: 67.44361954452641

Iteration 28 out of 100
Ratings for 100 particles updated, took: 7.731930732727051
Best rating for the current iteration: 67.49798070473585
Total best rating: 67.49798070473585

Iteration 29 out of 100
Ratings for 100 particles updated, took: 7.802476167678833
Best rating for the current iteration: 67.72074446762888
Total best rating: 67.72074446762888

Iteration 30 out of 100
Ratings for 100 particles updated, took: 7.884815692901611
Best rating for the current iteration: 67.72074446762888
Total best rating: 67.72074446762888

Iteration 31 out of 100
Ratings for 100 particles updated, took: 7.856792449951172
Best rating for the current iteration: 67.85065652903354
Total best rating: 67.85065652903354

Iteration 32 out of 100
Ratings for 100 particles updated, took: 7.910067558288574
Best rating for the current iteration: 67.87123656659686
Total best rating: 67.87123656659686

Iteration 33 out of 100
Ratings for 100 particles updated, took: 7.963075876235962
Best rating for the current iteration: 68.036535077738
Total best rating: 68.036535077738

Iteration 34 out of 100
Ratings for 100 particles updated, took: 7.866111755371094
Best rating for the current iteration: 68.036535077738
Total best rating: 68.036535077738

Iteration 35 out of 100
Ratings for 100 particles updated, took: 7.874396085739136
Best rating for the current iteration: 68.29785340254224
Total best rating: 68.29785340254224

Iteration 36 out of 100
Ratings for 100 particles updated, took: 7.807852029800415
Best rating for the current iteration: 68.29785340254224
Total best rating: 68.29785340254224

Iteration 37 out of 100
Ratings for 100 particles updated, took: 7.901883840560913
Best rating for the current iteration: 68.39606209822101
Total best rating: 68.39606209822101

Iteration 38 out of 100
Ratings for 100 particles updated, took: 7.902080059051514
Best rating for the current iteration: 68.52651210024814
Total best rating: 68.52651210024814

Iteration 39 out of 100
Ratings for 100 particles updated, took: 7.7564921379089355
Best rating for the current iteration: 68.63478793513623
Total best rating: 68.63478793513623

Iteration 40 out of 100
Ratings for 100 particles updated, took: 7.822022914886475
Best rating for the current iteration: 68.75031835000361
Total best rating: 68.75031835000361

Iteration 41 out of 100
Ratings for 100 particles updated, took: 7.752381324768066
Best rating for the current iteration: 69.00326726303277
Total best rating: 69.00326726303277

Iteration 42 out of 100
Ratings for 100 particles updated, took: 7.723973035812378
Best rating for the current iteration: 69.00326726303277
Total best rating: 69.00326726303277

Iteration 43 out of 100
Ratings for 100 particles updated, took: 7.757134675979614
Best rating for the current iteration: 69.08106846640649
Total best rating: 69.08106846640649

Iteration 44 out of 100
Ratings for 100 particles updated, took: 7.775444269180298
Best rating for the current iteration: 69.3589466524771
Total best rating: 69.3589466524771

Iteration 45 out of 100
Ratings for 100 particles updated, took: 7.837208271026611
Best rating for the current iteration: 69.45705701364793
Total best rating: 69.45705701364793

Iteration 46 out of 100
Ratings for 100 particles updated, took: 7.7558183670043945
Best rating for the current iteration: 69.61424449059572
Total best rating: 69.61424449059572

Iteration 47 out of 100
Ratings for 100 particles updated, took: 7.666982412338257
Best rating for the current iteration: 69.61424449059572
Total best rating: 69.61424449059572

Iteration 48 out of 100
Ratings for 100 particles updated, took: 7.647786617279053
Best rating for the current iteration: 69.64077197968646
Total best rating: 69.64077197968646

Iteration 49 out of 100
Ratings for 100 particles updated, took: 7.661352872848511
Best rating for the current iteration: 69.68533548839835
Total best rating: 69.68533548839835

Iteration 50 out of 100
Ratings for 100 particles updated, took: 7.640978097915649
Best rating for the current iteration: 69.84092545128854
Total best rating: 69.84092545128854

Iteration 51 out of 100
Ratings for 100 particles updated, took: 7.698811292648315
Best rating for the current iteration: 69.91177385008466
Total best rating: 69.91177385008466

Iteration 52 out of 100
Ratings for 100 particles updated, took: 7.680701732635498
Best rating for the current iteration: 70.09070645770889
Total best rating: 70.09070645770889

Iteration 53 out of 100
Ratings for 100 particles updated, took: 7.652737140655518
Best rating for the current iteration: 70.17218469524475
Total best rating: 70.17218469524475

Iteration 54 out of 100
Ratings for 100 particles updated, took: 7.638884782791138
Best rating for the current iteration: 70.28832597328748
Total best rating: 70.28832597328748

Iteration 55 out of 100
Ratings for 100 particles updated, took: 7.630095958709717
Best rating for the current iteration: 70.29216251788986
Total best rating: 70.29216251788986

Iteration 56 out of 100
Ratings for 100 particles updated, took: 7.621424198150635
Best rating for the current iteration: 70.35185453096003
Total best rating: 70.35185453096003

Iteration 57 out of 100
Ratings for 100 particles updated, took: 7.619642972946167
Best rating for the current iteration: 70.39124989703501
Total best rating: 70.39124989703501

Iteration 58 out of 100
Ratings for 100 particles updated, took: 7.615821838378906
Best rating for the current iteration: 70.60707433875506
Total best rating: 70.60707433875506

Iteration 59 out of 100
Ratings for 100 particles updated, took: 7.646274566650391
Best rating for the current iteration: 70.68796108173345
Total best rating: 70.68796108173345

Iteration 60 out of 100
Ratings for 100 particles updated, took: 7.604333400726318
Best rating for the current iteration: 70.75981190945214
Total best rating: 70.75981190945214

Iteration 61 out of 100
Ratings for 100 particles updated, took: 7.606186866760254
Best rating for the current iteration: 70.86521798789988
Total best rating: 70.86521798789988

Iteration 62 out of 100
Ratings for 100 particles updated, took: 7.605030298233032
Best rating for the current iteration: 70.95117642196584
Total best rating: 70.95117642196584

Iteration 63 out of 100
Ratings for 100 particles updated, took: 7.599790334701538
Best rating for the current iteration: 70.95117642196584
Total best rating: 70.95117642196584

Iteration 64 out of 100
Ratings for 100 particles updated, took: 7.589601278305054
Best rating for the current iteration: 70.95117642196584
Total best rating: 70.95117642196584

Iteration 65 out of 100
Ratings for 100 particles updated, took: 7.598105192184448
Best rating for the current iteration: 70.95117642196584
Total best rating: 70.95117642196584

Iteration 66 out of 100
Ratings for 100 particles updated, took: 7.574886798858643
Best rating for the current iteration: 70.96513454884033
Total best rating: 70.96513454884033

Iteration 67 out of 100
Ratings for 100 particles updated, took: 7.556926727294922
Best rating for the current iteration: 71.02237894872842
Total best rating: 71.02237894872842

Iteration 68 out of 100
Ratings for 100 particles updated, took: 7.573696851730347
Best rating for the current iteration: 71.11648238697353
Total best rating: 71.11648238697353

Iteration 69 out of 100
Ratings for 100 particles updated, took: 7.5630199909210205
Best rating for the current iteration: 71.12935167430302
Total best rating: 71.12935167430302

Iteration 70 out of 100
Ratings for 100 particles updated, took: 7.592172145843506
Best rating for the current iteration: 71.24953332050251
Total best rating: 71.24953332050251

Iteration 71 out of 100
Ratings for 100 particles updated, took: 7.590760231018066
Best rating for the current iteration: 71.24953332050251
Total best rating: 71.24953332050251

Iteration 72 out of 100
Ratings for 100 particles updated, took: 7.606580018997192
Best rating for the current iteration: 71.34241911770016
Total best rating: 71.34241911770016

Iteration 73 out of 100
Ratings for 100 particles updated, took: 7.6075427532196045
Best rating for the current iteration: 71.34677725065393
Total best rating: 71.34677725065393

Iteration 74 out of 100
Ratings for 100 particles updated, took: 7.597656488418579
Best rating for the current iteration: 71.38714352129341
Total best rating: 71.38714352129341

Iteration 75 out of 100
Ratings for 100 particles updated, took: 7.606231927871704
Best rating for the current iteration: 71.46561527213727
Total best rating: 71.46561527213727

Iteration 76 out of 100
Ratings for 100 particles updated, took: 7.610247373580933
Best rating for the current iteration: 71.53550791095962
Total best rating: 71.53550791095962

Iteration 77 out of 100
Ratings for 100 particles updated, took: 7.598643064498901
Best rating for the current iteration: 71.65758374242874
Total best rating: 71.65758374242874

Iteration 78 out of 100
Ratings for 100 particles updated, took: 7.630087852478027
Best rating for the current iteration: 71.66040051685698
Total best rating: 71.66040051685698

Iteration 79 out of 100
Ratings for 100 particles updated, took: 7.621565341949463
Best rating for the current iteration: 71.68508963624706
Total best rating: 71.68508963624706

Iteration 80 out of 100
Ratings for 100 particles updated, took: 7.575258016586304
Best rating for the current iteration: 71.69274834719832
Total best rating: 71.69274834719832

Iteration 81 out of 100
Ratings for 100 particles updated, took: 7.598518371582031
Best rating for the current iteration: 71.7184631142325
Total best rating: 71.7184631142325

Iteration 82 out of 100
Ratings for 100 particles updated, took: 7.594447612762451
Best rating for the current iteration: 71.80794878742324
Total best rating: 71.80794878742324

Iteration 83 out of 100
Ratings for 100 particles updated, took: 7.645975589752197
Best rating for the current iteration: 71.89586894772329
Total best rating: 71.89586894772329

Iteration 84 out of 100
Ratings for 100 particles updated, took: 7.617581844329834
Best rating for the current iteration: 71.96182658886191
Total best rating: 71.96182658886191

Iteration 85 out of 100
Ratings for 100 particles updated, took: 7.608736276626587
Best rating for the current iteration: 71.9818302030314
Total best rating: 71.9818302030314

Iteration 86 out of 100
Ratings for 100 particles updated, took: 7.589261293411255
Best rating for the current iteration: 72.10884201291688
Total best rating: 72.10884201291688

Iteration 87 out of 100
Ratings for 100 particles updated, took: 7.592673301696777
Best rating for the current iteration: 72.25324937093491
Total best rating: 72.25324937093491

Iteration 88 out of 100
Ratings for 100 particles updated, took: 7.566508531570435
Best rating for the current iteration: 72.32650604878606
Total best rating: 72.32650604878606

Iteration 89 out of 100
Ratings for 100 particles updated, took: 7.595083236694336
Best rating for the current iteration: 72.34369684979126
Total best rating: 72.34369684979126

Iteration 90 out of 100
Ratings for 100 particles updated, took: 7.595831871032715
Best rating for the current iteration: 72.48619470654867
Total best rating: 72.48619470654867

Iteration 91 out of 100
Ratings for 100 particles updated, took: 7.597483396530151
Best rating for the current iteration: 72.48619470654867
Total best rating: 72.48619470654867

Iteration 92 out of 100
Ratings for 100 particles updated, took: 7.562389612197876
Best rating for the current iteration: 72.56848582356389
Total best rating: 72.56848582356389

Iteration 93 out of 100
Ratings for 100 particles updated, took: 7.597841024398804
Best rating for the current iteration: 72.63436899431912
Total best rating: 72.63436899431912

Iteration 94 out of 100
Ratings for 100 particles updated, took: 7.6065192222595215
Best rating for the current iteration: 72.64754083240344
Total best rating: 72.64754083240344

Iteration 95 out of 100
Ratings for 100 particles updated, took: 7.581718921661377
Best rating for the current iteration: 72.89891939389628
Total best rating: 72.89891939389628

Iteration 96 out of 100
Ratings for 100 particles updated, took: 7.60517954826355
Best rating for the current iteration: 72.94817317483916
Total best rating: 72.94817317483916

Iteration 97 out of 100
Ratings for 100 particles updated, took: 7.6098058223724365
Best rating for the current iteration: 72.99764113454634
Total best rating: 72.99764113454634

Iteration 98 out of 100
Ratings for 100 particles updated, took: 7.570795059204102
Best rating for the current iteration: 73.04198207334889
Total best rating: 73.04198207334889

Iteration 99 out of 100
Ratings for 100 particles updated, took: 7.594786167144775
Best rating for the current iteration: 73.08545925328937
Total best rating: 73.08545925328937

Iteration 100 out of 100
Ratings for 100 particles updated, took: 7.556993007659912
Best rating for the current iteration: 73.14638382167688
Total best rating: 73.14638382167688

In [25]:
print("Best rating:", best_rating)
print("Time taken:", time() - time_start)

Best rating: 73.14638382167688
Time taken: 922.0956757068634

## Выгрузка решения

In [26]:
def output_csv(df, filename, with_index=False):
    df_dirpath = Path(r"./solutions")
    df_dirpath.mkdir(parents=True, exist_ok=True)

    df_filepath = df_dirpath / filename

    with df_filepath.open("w") as f:
        df.to_csv(f, sep=";", lineterminator="\n", index=with_index)

In [27]:
df_solution = pd.DataFrame(best_solution, index=items_id, columns=stores_id).stack()
df_full[col_dist] = df_solution.reindex(df_full.index).values
df_full

                    Объём товара в закрывающемся магазине (V)  \
Код товара Магазин
226249     54                                            10.0
           56                                            10.0
           57                                            10.0
           60                                            10.0
           61                                            10.0
...                                                       ...
239221     88                                             NaN
           105                                            NaN
           29                                             NaN
           27                                             NaN
           113                                           17.0

                    Продажи товара в магазине (S)  \
Код товара Магазин
226249     54                            1.379157
           56                            0.943567
           57                            0.857143
           60                            0.406742
           61                            0.713024
...                                           ...
239221     88                                 NaN
           105                                NaN
           29                                 NaN
           27                                 NaN
           113                           0.302326

                    Максимальная вместимость товара в магазине (M)  \
Код товара Магазин
226249     54                                                  8.0
           56                                                  8.0
           57                                                  8.0
           60                                                  8.0
           61                                                  8.0
...                                                            ...
239221     88                                                  NaN
           105                                                 NaN
           29                                                  NaN
           27                                                  NaN
           113                                                10.0

                    Остаток товара в магазине (R)  Распределение частиц
Код товара Магазин
226249     54                                16.0                     0
           56                                22.0                     0
           57                                19.0                     0
           60                                28.0                     0
           61                                22.0                     0
...                                           ...                   ...
239221     88                                 NaN                     0
           105                                NaN                     0
           29                                 NaN                     0
           27                                 NaN                     0
           113                                5.0                     0

[525868 rows x 5 columns]

In [28]:
output_csv(df_full.dropna(), "swarm_solution.csv", with_index=True)